/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InputPanel.java
 *
 * Created on Jan 4, 2011, 4:28:25 PM
 */

package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.JCheckBox;
import javax.swing.JTextField;

/**
 *
 * @author Tuan Vu
 */
public class InputPanel extends javax.swing.JPanel implements ActionListener{
    JCheckBox tList[] = new JCheckBox[32];
    JCheckBox hList[] = new JCheckBox[4];
    JCheckBox bList [] = new JCheckBox[32];
    HashMap<String, JCheckBox> map = new HashMap<String, JCheckBox>();

    /** Creates new form InputPanel */
    public InputPanel() {
        initComponents();
        tList[0] =  r11;
        tList[1] =   r12;
        tList[2] =   r13;
        tList[3] =   r14;
        tList[4] =   r15;
        tList[5] =   r16;
        tList[6] =   r17;
        tList[7] =   r18;
        tList[8] =   r21;
        tList[9] =   r22;
        tList[10] =   r23;
        tList[11] =   r24;
        tList[12] =   r25;
        tList[13] =   r26;
        tList[14] =   r27;
        tList[15] =   r28;
        tList[16] =   r31;
        tList[17] =   r32;
        tList[18] =   r33;
        tList[19] =   r34;
        tList[20] =   r35;
        tList[21] =   r36;
        tList[22] =   r37;
        tList[23] =   r38;
        tList[24] =   r41;
        tList[25] =   r42;
        tList[26] =   r43;
        tList[27] =   r44;
        tList[28] =   r45;
        tList[29] =   r46;
        tList[30] =   r47;
        tList[31] =   r48;

        for (int i = 0; i< 8;i++) {
            String s = "r1"+(i+1);
            map.put(s, tList[i]);
        }
        for (int i = 8; i< 16;i++) {
            String s = "r2"+(i-7);
            map.put(s, tList[i]);
        }
        for (int i = 16; i< 24;i++) {
            String s = "r3"+(i-15);
            map.put(s, tList[i]);
        }
        for (int i = 24; i< 32;i++) {
            String s = "r3"+(i-23);
            map.put(s, tList[i]);
        }
        ActionListener al = new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r11ActionPerformed(evt);
            }
        };

        ActionListener al2 = new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ActionPerformed(evt);
            }
        };
        for (int i = 1; i < 32;i++) {
            tList[i].addActionListener(al);
        }

        hList[0] = h1;
        hList[1] = h2;
        hList[2] = h3;
        hList[3] = h4;

        for (int i = 1; i < 4;i++) {
            hList[i].addActionListener(al2);
        }

        for (int i =0; i < 8 ; i ++) {
            bList[i] = tList[7-i];
        }
        System.arraycopy(tList, 8, bList, 8, 16 - 8);
        int j=0;
        while (j<8) {
            bList[j+16] = tList[23-j];
            j++;
        }

        System.arraycopy(tList, 24, bList, 24, 32 - 24);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        r11 = new javax.swing.JCheckBox();
        r13 = new javax.swing.JCheckBox();
        r12 = new javax.swing.JCheckBox();
        r15 = new javax.swing.JCheckBox();
        r14 = new javax.swing.JCheckBox();
        r17 = new javax.swing.JCheckBox();
        r16 = new javax.swing.JCheckBox();
        r18 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        r25 = new javax.swing.JCheckBox();
        r24 = new javax.swing.JCheckBox();
        r23 = new javax.swing.JCheckBox();
        r22 = new javax.swing.JCheckBox();
        r21 = new javax.swing.JCheckBox();
        r26 = new javax.swing.JCheckBox();
        r27 = new javax.swing.JCheckBox();
        r28 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        r31 = new javax.swing.JCheckBox();
        r33 = new javax.swing.JCheckBox();
        r32 = new javax.swing.JCheckBox();
        r35 = new javax.swing.JCheckBox();
        r34 = new javax.swing.JCheckBox();
        r37 = new javax.swing.JCheckBox();
        r36 = new javax.swing.JCheckBox();
        r38 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        r42 = new javax.swing.JCheckBox();
        r43 = new javax.swing.JCheckBox();
        r44 = new javax.swing.JCheckBox();
        r45 = new javax.swing.JCheckBox();
        r46 = new javax.swing.JCheckBox();
        r47 = new javax.swing.JCheckBox();
        r48 = new javax.swing.JCheckBox();
        r41 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        h1 = new javax.swing.JCheckBox();
        h2 = new javax.swing.JCheckBox();
        h4 = new javax.swing.JCheckBox();
        h3 = new javax.swing.JCheckBox();
        cbxRs = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cbxAll = new javax.swing.JCheckBox();
        tfTarget = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(qlpm.QLPMApp.class).getContext().getResourceMap(InputPanel.class);
        r11.setText(resourceMap.getString("r11.text")); // NOI18N
        r11.setName("r11"); // NOI18N
        r11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r11ActionPerformed(evt);
            }
        });

        r13.setName("r13"); // NOI18N

        r12.setText(resourceMap.getString("r12.text")); // NOI18N
        r12.setName("r12"); // NOI18N

        r15.setName("r15"); // NOI18N

        r14.setName("r14"); // NOI18N

        r17.setName("r17"); // NOI18N

        r16.setName("r16"); // NOI18N

        r18.setName("r18"); // NOI18N
        r18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(r12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(r18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(r16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r13)
                        .addGap(44, 44, 44))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r18)
                    .addComponent(r17)
                    .addComponent(r16)
                    .addComponent(r15)
                    .addComponent(r14)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(r11)
                        .addComponent(r12))
                    .addComponent(r13)))
        );

        jPanel2.setName("jPanel2"); // NOI18N

        r25.setText(resourceMap.getString("r25.text")); // NOI18N
        r25.setName("r25"); // NOI18N

        r24.setText(resourceMap.getString("r24.text")); // NOI18N
        r24.setName("r24"); // NOI18N

        r23.setText(resourceMap.getString("r23.text")); // NOI18N
        r23.setName("r23"); // NOI18N

        r22.setText(resourceMap.getString("r22.text")); // NOI18N
        r22.setName("r22"); // NOI18N

        r21.setText(resourceMap.getString("r21.text")); // NOI18N
        r21.setName("r21"); // NOI18N

        r26.setText(resourceMap.getString("r26.text")); // NOI18N
        r26.setName("r26"); // NOI18N

        r27.setName("r27"); // NOI18N

        r28.setName("r28"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(r21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(r23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r28)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(r21)
                        .addComponent(r22)
                        .addComponent(r23)
                        .addComponent(r24)
                        .addComponent(r25)
                        .addComponent(r26))
                    .addComponent(r27, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(r28, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jPanel3.setName("jPanel3"); // NOI18N

        r31.setName("r31"); // NOI18N

        r33.setName("r33"); // NOI18N

        r32.setName("r32"); // NOI18N

        r35.setName("r35"); // NOI18N

        r34.setName("r34"); // NOI18N

        r37.setName("r37"); // NOI18N

        r36.setName("r36"); // NOI18N

        r38.setName("r38"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(r31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r32)
                .addGap(2, 2, 2)
                .addComponent(r33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(r35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r38)
                .addGap(216, 216, 216))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r34)
                    .addComponent(r35)
                    .addComponent(r31)
                    .addComponent(r32)
                    .addComponent(r33)
                    .addComponent(r36)
                    .addComponent(r37)
                    .addComponent(r38))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setName("jPanel4"); // NOI18N

        r42.setName("r42"); // NOI18N

        r43.setName("r43"); // NOI18N

        r44.setName("r44"); // NOI18N

        r45.setName("r45"); // NOI18N

        r46.setName("r46"); // NOI18N

        r47.setName("r47"); // NOI18N

        r48.setName("r48"); // NOI18N

        r41.setName("r41"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(r48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r47, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r46, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r45, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r44, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r43, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r42, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(r41, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(r42)
                    .addComponent(r43)
                    .addComponent(r44)
                    .addComponent(r45)
                    .addComponent(r46)
                    .addComponent(r47)
                    .addComponent(r48)
                    .addComponent(r41))
                .addContainerGap())
        );

        jPanel5.setName("jPanel5"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)))
        );

        jPanel6.setName("jPanel6"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)))
        );

        jPanel7.setName("jPanel7"); // NOI18N

        h1.setName("h1"); // NOI18N
        h1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ActionPerformed(evt);
            }
        });

        h2.setName("h2"); // NOI18N
        h2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2ActionPerformed(evt);
            }
        });

        h4.setName("h4"); // NOI18N

        h3.setName("h3"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(h1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h2))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(h4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h3)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(h1)
                    .addComponent(h2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(h3)
                    .addComponent(h4)))
        );

        cbxRs.setText(resourceMap.getString("cbxRs.text")); // NOI18N
        cbxRs.setName("cbxRs"); // NOI18N
        cbxRs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRsActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        cbxAll.setText(resourceMap.getString("cbxAll.text")); // NOI18N
        cbxAll.setName("cbxAll"); // NOI18N
        cbxAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAllActionPerformed(evt);
            }
        });

        tfTarget.setText(resourceMap.getString("tfTarget.text")); // NOI18N
        tfTarget.setName("tfTarget"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, 0, 176, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, 0, 196, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxRs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxAll)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, 0, 25, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxRs)
                            .addComponent(cbxAll))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void r18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r18ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_r18ActionPerformed

    private void r11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r11ActionPerformed
        // TODO add your handling code here:
        if (!tList[0].isEnabled()) return;
        String s = "";
        boolean on = false;
        for (int i = 0; i < 32; i++) {
            if (tList[i].isSelected()) {
                s+= "R" + convertToTarget(i) + " ";
                on = true;
            }
        }
        tfTarget.setText(s);
        setH(!on);
    }//GEN-LAST:event_r11ActionPerformed

    private void h1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ActionPerformed
        // TODO add your handling code here:
        if (!hList[0].isEnabled()) return;
        String s = "";
        boolean on = false;
        for (int i = 0; i < 4; i++) {
            if (hList[i].isSelected()) {
                s+= "H" + convertToTarget(i) + " ";
                on = true;
            }
        }
        tfTarget.setText(s);
        setL(!on);
    }//GEN-LAST:event_h1ActionPerformed

    private void h2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h2ActionPerformed

    private void cbxRsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRsActionPerformed
        // TODO add your handling code here:
        if (!tList[0].isEnabled()) return;
        String s = "";
        boolean on = false;

        for (int i = 0; i < 32; i++) {

            if (tList[i].isSelected()) {
                s+= "R" + convertToTarget(i) + " ";
                on = true;
            }
        }
        tfTarget.setText(s);
    }//GEN-LAST:event_cbxRsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tfTarget.setText("");

        for (int i = 0; i < 32; i++) {
            tList[i].setSelected(false);
            tList[i].setEnabled(true);
        }

        for (int i = 0; i <4; i++) {
            hList[i].setSelected(false);
            hList[i].setEnabled(true);
        }

        cbxRs.setSelected(false);
        cbxRs.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAllActionPerformed
        // TODO add your handling code here:
        boolean t = cbxAll.isSelected();
        for (int i = 0; i < 32; i++) {
            tList[i].setSelected(t);
            //tList[i].setEnabled(true);
        }

        for (int i = 0; i <4; i++) {
            //hList[i].setSelected(false);
            hList[i].setEnabled(!t);
        }
    }//GEN-LAST:event_cbxAllActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String s = "";
        //boolean cont= true;
        int i = 0;
        int j =-1;
        while (i<15) {
            if (bList[i].isSelected()) {
                s += "R" + convertToBridge(i);
                j = i;
                i=15;
            }
            i++;
        }
        i=15;
        if (j>0)
        while (j<i) {
            if (bList[i].isSelected()) {
                s += "-" + convertToBridge(i);
                i=0;
            }
            i--;
        }
        j=-1;
        i = 16;
        while (i<31) {
            if (bList[i].isSelected()) {
                s += "R" + convertToBridge(i);
                j = i;
                i=32;
            }
            i++;
        }
        i=31;
        if (j>15)
        while (j<i) {
            if (bList[i].isSelected()) {
                s += "-" + convertToBridge(i);
                i=0;
            }
            i--;
        }
        tfTarget.setText(s);

    }//GEN-LAST:event_jButton3ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbxAll;
    private javax.swing.JCheckBox cbxRs;
    private javax.swing.JCheckBox h1;
    private javax.swing.JCheckBox h2;
    private javax.swing.JCheckBox h3;
    private javax.swing.JCheckBox h4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JCheckBox r11;
    private javax.swing.JCheckBox r12;
    private javax.swing.JCheckBox r13;
    private javax.swing.JCheckBox r14;
    private javax.swing.JCheckBox r15;
    private javax.swing.JCheckBox r16;
    private javax.swing.JCheckBox r17;
    private javax.swing.JCheckBox r18;
    private javax.swing.JCheckBox r21;
    private javax.swing.JCheckBox r22;
    private javax.swing.JCheckBox r23;
    private javax.swing.JCheckBox r24;
    private javax.swing.JCheckBox r25;
    private javax.swing.JCheckBox r26;
    private javax.swing.JCheckBox r27;
    private javax.swing.JCheckBox r28;
    private javax.swing.JCheckBox r31;
    private javax.swing.JCheckBox r32;
    private javax.swing.JCheckBox r33;
    private javax.swing.JCheckBox r34;
    private javax.swing.JCheckBox r35;
    private javax.swing.JCheckBox r36;
    private javax.swing.JCheckBox r37;
    private javax.swing.JCheckBox r38;
    private javax.swing.JCheckBox r41;
    private javax.swing.JCheckBox r42;
    private javax.swing.JCheckBox r43;
    private javax.swing.JCheckBox r44;
    private javax.swing.JCheckBox r45;
    private javax.swing.JCheckBox r46;
    private javax.swing.JCheckBox r47;
    private javax.swing.JCheckBox r48;
    private javax.swing.JTextField tfTarget;
    // End of variables declaration//GEN-END:variables

    private String convertToTarget (int u) {
        int j = 1;
        if (cbxRs.isSelected()) j = 5;
        String s = "";
        s += ((u/8) +j);
        s += ((u%8) +1);
        return s;
    }

    private String convertToBridge (int u) {
        String s = "";
        if ((u>=8 && u <16) ||(u>=24)){
            int j = 1;
            if (cbxRs.isSelected()) j = 5;

            s += ((u/8) +j);
            s += ((u%8) +1);
        } else {
            if (u<8) {
                u = 7-u;

            } else
            if ( u>=16) {
                u = 39-u;
            }
            int j = 1;
                if (cbxRs.isSelected()) j = 5;

                s += ((u/8) +j);
                s += ((u%8) +1);
        }
        return s;

    }
    public void actionPerformed(ActionEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    private void setH (boolean en) {
        for (int i = 0; i<4; i ++) {
            hList[i].setEnabled(en);
            //hList[i].setSelected(en);
        }
    }
    private void setL (boolean en) {
        for (int i = 0; i<32; i ++) {
            tList[i].setEnabled(en);

        }
    }

    public String getResultString() {
        return tfTarget.getText();
    }

    public void setResultTarget(String tfTarget) {
        this.tfTarget.setText(tfTarget);
    }


}
